#!/usr/bin/env python3
"""
patch_crops_db.py
=================
Phase 1 & 2: AcreLogic crop database data-integrity patch.

Actions performed:
  1. Remove true duplicates (wolfberry==goji, honeyberry duplicate,
     dragon_tongue_bean duplicate, fababean==fava_bean)
  2. Reclassify Cowpeas (Iron & Clay) → Cover Crop
  3. Reclassify Forage Rape → Cover Crop  
  4. Fill missing feed_class values by category heuristic
  5. Add new high-value crops:
       Mizuna (Red), Mizuna (Green),
       Claytonia (Miner's Lettuce),
       Ranunculus, Snapdragon, Scabiosa, Sweet Pea,
       Pearl Onion (White), Spring Onion (White Lisbon),
       Garlic (Chesnok Red), Garlic (Softneck Silverskin),
       Delicata Squash, Acorn Squash (Honey Bear), Sugar Pumpkin (New England Pie)
"""

import json
import copy
import sys
from pathlib import Path

CROPS_FILE = Path(__file__).parent.parent / "src" / "data" / "crops.json"

# ── feed_class heuristic map ─────────────────────────────────────────────────
CATEGORY_FEED_CLASS = {
    "Nightshade": "heavy",      # tomatoes/peppers/eggplant are heavy feeders
    "Cucurbit":   "heavy",      # squash/cucumbers are heavy feeders
    "Brassica":   "medium",     # moderate-heavy but treated as medium in rotation
    "Herb":       "light",      # most herbs are light feeders
    "Flower":     "flower",
    "Fruit":      "fruit",
    "Grain":      "grain",
    "Cover Crop": "cover_crop",
    "Legume":     "legume",
    "Greens":     "light",
    "Root":       "light",
    "Tuber":      "medium",
    "Allium":     "medium",
    "Specialty":  "medium",
}

# ── IDs to remove (replaced by canonical entry) ──────────────────────────────
REMOVE_IDS = {
    "wolfberry",                # duplicate of goji_berry (same plant: Lycium barbarum)
    "honeyberry",               # duplicate of honeyberry_standard (Aurora variety is canonical)
    "fababean",                 # duplicate of fava_beans (Vicia faba, different spelling)
    "bean_dragon_tongue",       # duplicate of bush_bean_dragon_tongue
}

# ── Reclassification map: id → new category + feed_class ─────────────────────
RECLASSIFY = {
    "cowpeas_iron_clay": {"category": "Cover Crop", "feed_class": "cover_crop"},
    "forage_rape":       {"category": "Cover Crop", "feed_class": "cover_crop"},
}

# ── New crops to add ─────────────────────────────────────────────────────────
NEW_CROPS = [
    # ── Greens ──────────────────────────────────────────────────────────────
    {
        "id": "mizuna_red",
        "name": "Mizuna",
        "variety": "Red",
        "category": "Brassica",
        "emoji": "🥬",
        "dtm": 21,
        "harvest_window_days": 14,
        "seed_type": "DS",
        "seed_start_weeks_before_transplant": None,
        "season": "cool",
        "min_frost_free_days": 21,
        "max_temp_f": 75,
        "rows_per_30in_bed": 4,
        "in_row_spacing_in": 4,
        "row_spacing_in": 6,
        "seed_oz_per_100ft": 0.5,
        "loss_buffer_pct": 15,
        "yield_lbs_per_100ft": 70,
        "yield_unit": "lbs",
        "yield_bunches_per_100ft": 70,
        "wholesale_price_per_lb": 8,
        "wholesale_price_per_bunch": 3.50,
        "organic_premium_pct": 30,
        "jang_seeder": None,
        "feed_class": "light",
        "rotation_cannot_follow": ["brassica"],
        "rotation_prefers_after": ["legume", "cover_crop"],
        "interplant_compatible": ["radish", "spinach"],
        "notes": "Fast-growing salad mix staple. Succession every 2-3 weeks. Bolt-resistant in cool weather. Red variety adds visual interest to mix bags.",
        "harvest_count": 3,
        "harvest_notes": "Cut-and-come-again; harvest at 4-6 inches.",
        "csa_lbs_per_share": 0.25,
        "csa_share_unit": "lb",
        "csa_note": "Common in spring/fall salad mix shares.",
        "harvest_frequency": "Weekly",
        "harvest_method": "Scissor harvest or knife cut",
        "harvest_expectation": "70 lbs per 100ft",
        "frost_tolerant": True,
        "hard_frost": False,
        "frost_note": "Handles light frost; bolt-resistant in shoulder seasons.",
        "germination_rate_pct": 0.85,
        "seeds_per_packet": 500,
        "seed_price_usd": 3.49,
        "seed_unit": "seeds",
        "is_special_purchase": False,
        "late_transplant_tolerant": True,
        "planting_method": "Direct Seed",
        "seeds_per_oz": 18000,
    },
    {
        "id": "mizuna_green",
        "name": "Mizuna",
        "variety": "Green",
        "category": "Brassica",
        "emoji": "🥬",
        "dtm": 21,
        "harvest_window_days": 14,
        "seed_type": "DS",
        "seed_start_weeks_before_transplant": None,
        "season": "cool",
        "min_frost_free_days": 21,
        "max_temp_f": 75,
        "rows_per_30in_bed": 4,
        "in_row_spacing_in": 4,
        "row_spacing_in": 6,
        "seed_oz_per_100ft": 0.5,
        "loss_buffer_pct": 15,
        "yield_lbs_per_100ft": 75,
        "yield_unit": "lbs",
        "yield_bunches_per_100ft": 75,
        "wholesale_price_per_lb": 7,
        "wholesale_price_per_bunch": 3.00,
        "organic_premium_pct": 30,
        "jang_seeder": None,
        "feed_class": "light",
        "rotation_cannot_follow": ["brassica"],
        "rotation_prefers_after": ["legume", "cover_crop"],
        "interplant_compatible": ["radish", "spinach"],
        "notes": "Flagship CSA salad mix ingredient. Classic feathery green leaf. Succession every 2-3 weeks spring and fall.",
        "harvest_count": 3,
        "harvest_notes": "Cut-and-come-again at 4-6 inches.",
        "csa_lbs_per_share": 0.25,
        "csa_share_unit": "lb",
        "csa_note": "Standard salad mix component spring through fall.",
        "harvest_frequency": "Weekly",
        "harvest_method": "Scissor harvest or knife cut",
        "harvest_expectation": "75 lbs per 100ft",
        "frost_tolerant": True,
        "hard_frost": False,
        "frost_note": "Light frost tolerant to 28°F. Extends season well into fall.",
        "germination_rate_pct": 0.85,
        "seeds_per_packet": 500,
        "seed_price_usd": 3.49,
        "seed_unit": "seeds",
        "is_special_purchase": False,
        "late_transplant_tolerant": True,
        "planting_method": "Direct Seed",
        "seeds_per_oz": 18000,
    },
    {
        "id": "claytonia_miner",
        "name": "Claytonia",
        "variety": "Miner's Lettuce",
        "category": "Greens",
        "emoji": "🌿",
        "dtm": 40,
        "harvest_window_days": 21,
        "seed_type": "DS",
        "seed_start_weeks_before_transplant": None,
        "season": "cool",
        "min_frost_free_days": 40,
        "max_temp_f": 65,
        "rows_per_30in_bed": 5,
        "in_row_spacing_in": 3,
        "row_spacing_in": 5,
        "seed_oz_per_100ft": 0.25,
        "loss_buffer_pct": 20,
        "yield_lbs_per_100ft": 40,
        "yield_unit": "lbs",
        "yield_bunches_per_100ft": None,
        "wholesale_price_per_lb": 12,
        "wholesale_price_per_bunch": None,
        "organic_premium_pct": 35,
        "jang_seeder": None,
        "feed_class": "light",
        "rotation_cannot_follow": [],
        "rotation_prefers_after": ["legume", "cover_crop"],
        "interplant_compatible": ["radish", "spinach"],
        "notes": "Cold-hardy winter/early spring crop. Self-seeds readily. Unique round succulent leaves. Popular in winter CSA boxes and restaurant salad mix.",
        "harvest_count": 4,
        "harvest_notes": "Cut above crown, will regrow. Entire plant is edible.",
        "csa_lbs_per_share": 0.2,
        "csa_share_unit": "lb",
        "csa_note": "Premium winter green; add to salad mix or sell as standalone.",
        "harvest_frequency": "Every 2 weeks",
        "harvest_method": "Scissor harvest above crown",
        "harvest_expectation": "40 lbs per 100ft",
        "frost_tolerant": True,
        "hard_frost": True,
        "frost_note": "Survives hard frost; thrives in cold frames. One of the most frost-hardy greens available.",
        "germination_rate_pct": 0.70,
        "seeds_per_packet": 300,
        "seed_price_usd": 4.29,
        "seed_unit": "seeds",
        "is_special_purchase": False,
        "late_transplant_tolerant": True,
        "planting_method": "Direct Seed",
        "seeds_per_oz": 20000,
    },
    # ── Allium ───────────────────────────────────────────────────────────────
    {
        "id": "pearl_onion_white",
        "name": "Pearl Onion",
        "variety": "White",
        "category": "Allium",
        "emoji": "🧅",
        "dtm": 95,
        "harvest_window_days": 14,
        "seed_type": "DS",
        "seed_start_weeks_before_transplant": None,
        "season": "cool",
        "min_frost_free_days": 95,
        "max_temp_f": 85,
        "rows_per_30in_bed": 6,
        "in_row_spacing_in": 1,
        "row_spacing_in": 4,
        "seed_oz_per_100ft": 1.5,
        "loss_buffer_pct": 20,
        "yield_lbs_per_100ft": 45,
        "yield_unit": "lbs",
        "yield_bunches_per_100ft": None,
        "wholesale_price_per_lb": 4,
        "wholesale_price_per_bunch": None,
        "organic_premium_pct": 30,
        "jang_seeder": None,
        "feed_class": "medium",
        "rotation_cannot_follow": ["allium"],
        "rotation_prefers_after": ["legume", "cover_crop"],
        "interplant_compatible": ["carrot", "lettuce"],
        "notes": "Specialty pickled onion; also used fresh. Dense planting at 1 inch. Popular CSA fall box item. Cure like storage onions.",
        "harvest_count": 1,
        "harvest_notes": "Pull when tops fall over. Cure 2-3 weeks.",
        "csa_lbs_per_share": 0.5,
        "csa_share_unit": "lb",
        "csa_note": "Fall specialty item; excellent for pickling kits.",
        "harvest_frequency": "Once",
        "harvest_method": "Hand pull and cure",
        "harvest_expectation": "45 lbs per 100ft",
        "frost_tolerant": True,
        "hard_frost": False,
        "frost_note": "Cold-tolerant in early season; harvest before hard frost.",
        "germination_rate_pct": 0.75,
        "seeds_per_packet": 400,
        "seed_price_usd": 3.99,
        "seed_unit": "seeds",
        "is_special_purchase": False,
        "late_transplant_tolerant": False,
        "planting_method": "Direct Seed",
        "seeds_per_oz": 8500,
    },
    {
        "id": "spring_onion_white_lisbon",
        "name": "Spring Onion",
        "variety": "White Lisbon",
        "category": "Allium",
        "emoji": "🌱",
        "dtm": 60,
        "harvest_window_days": 21,
        "seed_type": "DS",
        "seed_start_weeks_before_transplant": None,
        "season": "cool",
        "min_frost_free_days": 60,
        "max_temp_f": 80,
        "rows_per_30in_bed": 8,
        "in_row_spacing_in": 1,
        "row_spacing_in": 3,
        "seed_oz_per_100ft": 1.0,
        "loss_buffer_pct": 15,
        "yield_lbs_per_100ft": 30,
        "yield_unit": "bunches",
        "yield_bunches_per_100ft": 60,
        "wholesale_price_per_lb": 3,
        "wholesale_price_per_bunch": 2.50,
        "organic_premium_pct": 25,
        "jang_seeder": None,
        "feed_class": "light",
        "rotation_cannot_follow": ["allium"],
        "rotation_prefers_after": ["legume", "cover_crop"],
        "interplant_compatible": ["carrot", "lettuce"],
        "notes": "True spring onion — thicker than scallions but not a storage onion. Succession every 3 weeks spring through fall. Distinct flavor profile from scallions.",
        "harvest_count": 1,
        "harvest_notes": "Pull at pencil thickness. Trim roots and wilted outer leaves.",
        "csa_lbs_per_share": 0.3,
        "csa_share_unit": "bunch",
        "csa_note": "Spring staple for CSA bundles.",
        "harvest_frequency": "Weekly succession",
        "harvest_method": "Hand pull",
        "harvest_expectation": "60 bunches per 100ft",
        "frost_tolerant": True,
        "hard_frost": False,
        "frost_note": "Light frost tolerant. Plant early spring as soon as soil workable.",
        "germination_rate_pct": 0.80,
        "seeds_per_packet": 400,
        "seed_price_usd": 3.49,
        "seed_unit": "seeds",
        "is_special_purchase": False,
        "late_transplant_tolerant": True,
        "planting_method": "Direct Seed",
        "seeds_per_oz": 8000,
    },
    {
        "id": "garlic_chesnok_red",
        "name": "Garlic",
        "variety": "Chesnok Red",
        "category": "Allium",
        "emoji": "🧄",
        "dtm": 260,
        "harvest_window_days": 14,
        "seed_type": "DS",
        "seed_start_weeks_before_transplant": None,
        "season": "cool",
        "min_frost_free_days": 260,
        "max_temp_f": 90,
        "rows_per_30in_bed": 3,
        "in_row_spacing_in": 6,
        "row_spacing_in": 10,
        "seed_oz_per_100ft": None,
        "loss_buffer_pct": 15,
        "yield_lbs_per_100ft": 35,
        "yield_unit": "lbs",
        "yield_bunches_per_100ft": None,
        "wholesale_price_per_lb": 6,
        "wholesale_price_per_bunch": None,
        "organic_premium_pct": 40,
        "jang_seeder": None,
        "feed_class": "medium",
        "rotation_cannot_follow": ["allium"],
        "rotation_prefers_after": ["legume", "cover_crop"],
        "interplant_compatible": ["tomato", "pepper"],
        "notes": "Purple-striped hardneck variety from Republic of Georgia. Strong complex flavor. Excellent for CSA garlic braids and farm stand. Fall plant, early summer harvest.",
        "harvest_count": 1,
        "harvest_notes": "Harvest when 4-5 lower leaves are brown. Cure 4-6 weeks.",
        "csa_lbs_per_share": 0.25,
        "csa_share_unit": "head",
        "csa_note": "CSA summer staple; customers expect fresh cured garlic.",
        "harvest_frequency": "Once",
        "harvest_method": "Hand pull, hang cure",
        "harvest_expectation": "35 lbs per 100ft",
        "frost_tolerant": True,
        "hard_frost": True,
        "frost_note": "Requires cold stratification to form cloves. Plant in fall 4-6 weeks before hard freeze.",
        "germination_rate_pct": 0.90,
        "seeds_per_packet": None,
        "seed_price_usd": 12.00,
        "seed_unit": "bulbs",
        "is_special_purchase": False,
        "late_transplant_tolerant": False,
        "planting_method": "Direct Seed (cloves)",
        "seeds_per_oz": None,
    },
    {
        "id": "garlic_softneck_silverskin",
        "name": "Garlic",
        "variety": "Softneck Silverskin",
        "category": "Allium",
        "emoji": "🧄",
        "dtm": 240,
        "harvest_window_days": 21,
        "seed_type": "DS",
        "seed_start_weeks_before_transplant": None,
        "season": "cool",
        "min_frost_free_days": 240,
        "max_temp_f": 95,
        "rows_per_30in_bed": 3,
        "in_row_spacing_in": 5,
        "row_spacing_in": 10,
        "seed_oz_per_100ft": None,
        "loss_buffer_pct": 15,
        "yield_lbs_per_100ft": 40,
        "yield_unit": "lbs",
        "yield_bunches_per_100ft": None,
        "wholesale_price_per_lb": 5,
        "wholesale_price_per_bunch": None,
        "organic_premium_pct": 30,
        "jang_seeder": None,
        "feed_class": "medium",
        "rotation_cannot_follow": ["allium"],
        "rotation_prefers_after": ["legume", "cover_crop"],
        "interplant_compatible": ["tomato", "pepper"],
        "notes": "Commercial standard softneck. Long shelf life (up to 12 months). Ideal for braiding. Stores better than hardneck — good for fall/winter CSA or market stalls. Adapts to warmer climates.",
        "harvest_count": 1,
        "harvest_notes": "Harvest when 5-6 leaves still green. Excellent curing durability.",
        "csa_lbs_per_share": 0.25,
        "csa_share_unit": "head",
        "csa_note": "Best long-storage garlic for CSA year-round programs.",
        "harvest_frequency": "Once",
        "harvest_method": "Hand pull or loosen soil with fork. Braid when cured.",
        "harvest_expectation": "40 lbs per 100ft",
        "frost_tolerant": True,
        "hard_frost": True,
        "frost_note": "More adaptable to warmer climates than hardneck varieties. Plant in fall.",
        "germination_rate_pct": 0.92,
        "seeds_per_packet": None,
        "seed_price_usd": 10.00,
        "seed_unit": "bulbs",
        "is_special_purchase": False,
        "late_transplant_tolerant": False,
        "planting_method": "Direct Seed (cloves)",
        "seeds_per_oz": None,
    },
    # ── Cucurbit additions ────────────────────────────────────────────────────
    {
        "id": "delicata_squash_jester",
        "name": "Delicata Squash",
        "variety": "Jester",
        "category": "Cucurbit",
        "emoji": "🎃",
        "dtm": 80,
        "harvest_window_days": 30,
        "seed_type": "DS",
        "seed_start_weeks_before_transplant": None,
        "season": "warm",
        "min_frost_free_days": 80,
        "max_temp_f": 95,
        "rows_per_30in_bed": 1,
        "in_row_spacing_in": 18,
        "row_spacing_in": 36,
        "seed_oz_per_100ft": 0.5,
        "loss_buffer_pct": 20,
        "yield_lbs_per_100ft": 100,
        "yield_unit": "lbs",
        "yield_bunches_per_100ft": None,
        "wholesale_price_per_lb": 2.50,
        "wholesale_price_per_bunch": None,
        "organic_premium_pct": 30,
        "jang_seeder": None,
        "feed_class": "heavy",
        "rotation_cannot_follow": ["cucurbit"],
        "rotation_prefers_after": ["legume", "cover_crop"],
        "interplant_compatible": ["nasturtium", "pole_bean"],
        "notes": "Most popular CSA winter squash. Short vines fit well in tight spaces. Edible skin means easier prep. Stores 3-4 months. Jester has excellent eye-appeal with its striped pattern.",
        "harvest_count": 6,
        "harvest_notes": "Harvest when stem is corky and skin resists fingernail. Leave 2-inch stem attached.",
        "csa_lbs_per_share": 1.5,
        "csa_share_unit": "lb",
        "csa_note": "Fall CSA anchor crop. Customers love delicata.",
        "harvest_frequency": "Weekly (mature fruits)",
        "harvest_method": "Hand harvest with clippers",
        "harvest_expectation": "100 lbs per 100ft",
        "frost_tolerant": False,
        "hard_frost": False,
        "frost_note": "Frost kills vines. Harvest all fruits at first frost warning.",
        "germination_rate_pct": 0.85,
        "seeds_per_packet": 20,
        "seed_price_usd": 4.49,
        "seed_unit": "seeds",
        "is_special_purchase": False,
        "late_transplant_tolerant": False,
        "planting_method": "Direct Seed",
        "seeds_per_oz": 200,
    },
    {
        "id": "acorn_squash_honey_bear",
        "name": "Acorn Squash",
        "variety": "Honey Bear",
        "category": "Cucurbit",
        "emoji": "🎃",
        "dtm": 85,
        "harvest_window_days": 30,
        "seed_type": "DS",
        "seed_start_weeks_before_transplant": None,
        "season": "warm",
        "min_frost_free_days": 85,
        "max_temp_f": 95,
        "rows_per_30in_bed": 1,
        "in_row_spacing_in": 24,
        "row_spacing_in": 36,
        "seed_oz_per_100ft": 0.5,
        "loss_buffer_pct": 20,
        "yield_lbs_per_100ft": 90,
        "yield_unit": "lbs",
        "yield_bunches_per_100ft": None,
        "wholesale_price_per_lb": 2.00,
        "wholesale_price_per_bunch": None,
        "organic_premium_pct": 25,
        "jang_seeder": None,
        "feed_class": "heavy",
        "rotation_cannot_follow": ["cucurbit"],
        "rotation_prefers_after": ["legume", "cover_crop"],
        "interplant_compatible": ["nasturtium", "pole_bean"],
        "notes": "Bush-type acorn squash — compact plants great for small farms. Honey Bear is AAS winner with good yields and excellent flavor. Single-serving size popular in CSA boxes.",
        "harvest_count": 5,
        "harvest_notes": "Dark green, hard skin. Cork-dry stem indicates maturity.",
        "csa_lbs_per_share": 1.0,
        "csa_share_unit": "squash",
        "csa_note": "Standard fall box item. Single-serve sizing.",
        "harvest_frequency": "Weekly (mature fruits)",
        "harvest_method": "Hand harvest with clippers",
        "harvest_expectation": "90 lbs per 100ft",
        "frost_tolerant": False,
        "hard_frost": False,
        "frost_note": "No frost tolerance. Harvest before any frost event.",
        "germination_rate_pct": 0.85,
        "seeds_per_packet": 20,
        "seed_price_usd": 4.79,
        "seed_unit": "seeds",
        "is_special_purchase": False,
        "late_transplant_tolerant": False,
        "planting_method": "Direct Seed",
        "seeds_per_oz": 180,
    },
    {
        "id": "sugar_pumpkin_new_england_pie",
        "name": "Sugar Pumpkin",
        "variety": "New England Pie",
        "category": "Cucurbit",
        "emoji": "🎃",
        "dtm": 100,
        "harvest_window_days": 30,
        "seed_type": "DS",
        "seed_start_weeks_before_transplant": None,
        "season": "warm",
        "min_frost_free_days": 100,
        "max_temp_f": 95,
        "rows_per_30in_bed": 1,
        "in_row_spacing_in": 24,
        "row_spacing_in": 60,
        "seed_oz_per_100ft": 0.5,
        "loss_buffer_pct": 20,
        "yield_lbs_per_100ft": 80,
        "yield_unit": "lbs",
        "yield_bunches_per_100ft": None,
        "wholesale_price_per_lb": 1.75,
        "wholesale_price_per_bunch": None,
        "organic_premium_pct": 25,
        "jang_seeder": None,
        "feed_class": "heavy",
        "rotation_cannot_follow": ["cucurbit"],
        "rotation_prefers_after": ["legume", "cover_crop"],
        "interplant_compatible": ["nasturtium"],
        "notes": "Classic baking/pie pumpkin. Dense sweet flesh — distinct from decorative pumpkins. 4-6 lb fruits. Popular fall CSA item especially near Thanksgiving. Stores 3+ months.",
        "harvest_count": 4,
        "harvest_notes": "Harvest when fully orange and stem is dry. Leave stem on.",
        "csa_lbs_per_share": 1.0,
        "csa_share_unit": "pumpkin",
        "csa_note": "Fall and Thanksgiving CSA anchor.",
        "harvest_frequency": "Weekly (mature fruits)",
        "harvest_method": "Hand harvest with clippers",
        "harvest_expectation": "80 lbs per 100ft",
        "frost_tolerant": False,
        "hard_frost": False,
        "frost_note": "Harvest before frost. Cured pumpkins handle light frost in storage.",
        "germination_rate_pct": 0.85,
        "seeds_per_packet": 20,
        "seed_price_usd": 3.99,
        "seed_unit": "seeds",
        "is_special_purchase": False,
        "late_transplant_tolerant": False,
        "planting_method": "Direct Seed",
        "seeds_per_oz": 120,
    },
    # ── Flowers ───────────────────────────────────────────────────────────────
    {
        "id": "ranunculus_tecolote",
        "name": "Ranunculus",
        "variety": "Tecolote Mix",
        "category": "Flower",
        "emoji": "🌸",
        "dtm": 90,
        "harvest_window_days": 28,
        "seed_type": "TP",
        "seed_start_weeks_before_transplant": 12,
        "season": "cool",
        "min_frost_free_days": 90,
        "max_temp_f": 65,
        "rows_per_30in_bed": 4,
        "in_row_spacing_in": 6,
        "row_spacing_in": 7,
        "seed_oz_per_100ft": None,
        "loss_buffer_pct": 25,
        "yield_lbs_per_100ft": None,
        "yield_unit": "stems",
        "yield_bunches_per_100ft": 100,
        "wholesale_price_per_lb": None,
        "wholesale_price_per_bunch": 12,
        "organic_premium_pct": 35,
        "jang_seeder": None,
        "feed_class": "flower",
        "rotation_cannot_follow": ["ranunculus"],
        "rotation_prefers_after": ["legume", "cover_crop"],
        "interplant_compatible": [],
        "notes": "Premier CSA and florist cut flower. Pre-soak corms 4-6 hours before planting. Plant claw-side-down in fall for spring bloom (mild climates) or very early spring. Tecolote is the commercial standard — large ruffled blooms in a wide color mix.",
        "harvest_count": 8,
        "harvest_notes": "Harvest when bud is paintbrush stage — just before petals open. 5-7 day vase life.",
        "csa_lbs_per_share": None,
        "csa_share_unit": "stems",
        "csa_note": "Premium flower CSA — 5-7 stems per share at peak harvest.",
        "harvest_frequency": "Every 3-4 days at peak",
        "harvest_method": "Cut at base of stem",
        "harvest_expectation": "100 stems per 100ft",
        "frost_tolerant": True,
        "hard_frost": False,
        "frost_note": "Corms rot in waterlogged or frozen soil. Use row cover below 28°F.",
        "germination_rate_pct": 0.70,
        "seeds_per_packet": None,
        "seed_price_usd": 18.00,
        "seed_unit": "corms",
        "is_special_purchase": False,
        "late_transplant_tolerant": False,
        "planting_method": "Corm/Bulb",
        "seeds_per_oz": None,
    },
    {
        "id": "snapdragon_potomac",
        "name": "Snapdragon",
        "variety": "Potomac Mix",
        "category": "Flower",
        "emoji": "🌸",
        "dtm": 90,
        "harvest_window_days": 35,
        "seed_type": "TP",
        "seed_start_weeks_before_transplant": 10,
        "season": "cool",
        "min_frost_free_days": 90,
        "max_temp_f": 70,
        "rows_per_30in_bed": 4,
        "in_row_spacing_in": 6,
        "row_spacing_in": 7,
        "seed_oz_per_100ft": None,
        "loss_buffer_pct": 20,
        "yield_lbs_per_100ft": None,
        "yield_unit": "stems",
        "yield_bunches_per_100ft": 120,
        "wholesale_price_per_lb": None,
        "wholesale_price_per_bunch": 7,
        "organic_premium_pct": 30,
        "jang_seeder": None,
        "feed_class": "flower",
        "rotation_cannot_follow": [],
        "rotation_prefers_after": ["legume"],
        "interplant_compatible": [],
        "notes": "Major cut flower. Spring and fall production (bolts in summer heat). Potomac series is the commercial standard for florists — tall spikes, wide color range. Pinch when young for branching. Excellent vase life 10-14 days.",
        "harvest_count": 6,
        "harvest_notes": "Harvest when 3-4 florets open from the bottom. Don't wait for top to open.",
        "csa_lbs_per_share": None,
        "csa_share_unit": "stems",
        "csa_note": "Spring/fall staple for flower CSA boxes.",
        "harvest_frequency": "Every 3-5 days",
        "harvest_method": "Cut stem at base. Snap off spent flowers.",
        "harvest_expectation": "120 stems per 100ft",
        "frost_tolerant": True,
        "hard_frost": False,
        "frost_note": "Light frost tolerant. Plant early spring, again in late summer for fall crop.",
        "germination_rate_pct": 0.78,
        "seeds_per_packet": 200,
        "seed_price_usd": 4.99,
        "seed_unit": "seeds",
        "is_special_purchase": False,
        "late_transplant_tolerant": False,
        "planting_method": "Transplant",
        "seeds_per_oz": 170000,
    },
    {
        "id": "scabiosa_tall_mixed",
        "name": "Scabiosa",
        "variety": "Tall Mixed",
        "category": "Flower",
        "emoji": "💜",
        "dtm": 75,
        "harvest_window_days": 42,
        "seed_type": "TP",
        "seed_start_weeks_before_transplant": 8,
        "season": "cool",
        "min_frost_free_days": 75,
        "max_temp_f": 75,
        "rows_per_30in_bed": 3,
        "in_row_spacing_in": 9,
        "row_spacing_in": 10,
        "seed_oz_per_100ft": None,
        "loss_buffer_pct": 20,
        "yield_lbs_per_100ft": None,
        "yield_unit": "stems",
        "yield_bunches_per_100ft": 90,
        "wholesale_price_per_lb": None,
        "wholesale_price_per_bunch": 9,
        "organic_premium_pct": 35,
        "jang_seeder": None,
        "feed_class": "flower",
        "rotation_cannot_follow": [],
        "rotation_prefers_after": ["legume"],
        "interplant_compatible": [],
        "notes": "Pincushion flower — premium specialty cut. Long vase life. Excellent pollinator attractor. Florists pay premium. Colors range from white to deep purple. Continuous harvest over 6+ weeks.",
        "harvest_count": 10,
        "harvest_notes": "Harvest when petals unfold but center still tight green. Recut stems.",
        "csa_lbs_per_share": None,
        "csa_share_unit": "stems",
        "csa_note": "Premium filler/accent for flower shares.",
        "harvest_frequency": "Every 3-4 days",
        "harvest_method": "Cut at base using sharp scissors",
        "harvest_expectation": "90 stems per 100ft",
        "frost_tolerant": True,
        "hard_frost": False,
        "frost_note": "Hardy to 25°F once established. Good shoulder-season cut.",
        "germination_rate_pct": 0.72,
        "seeds_per_packet": 100,
        "seed_price_usd": 4.29,
        "seed_unit": "seeds",
        "is_special_purchase": False,
        "late_transplant_tolerant": True,
        "planting_method": "Transplant",
        "seeds_per_oz": 4000,
    },
    {
        "id": "sweet_pea_royal_mix",
        "name": "Sweet Pea",
        "variety": "Royal Mix",
        "category": "Flower",
        "emoji": "🌸",
        "dtm": 75,
        "harvest_window_days": 28,
        "seed_type": "DS",
        "seed_start_weeks_before_transplant": None,
        "season": "cool",
        "min_frost_free_days": 75,
        "max_temp_f": 65,
        "rows_per_30in_bed": 2,
        "in_row_spacing_in": 6,
        "row_spacing_in": 15,
        "seed_oz_per_100ft": 1.0,
        "loss_buffer_pct": 20,
        "yield_lbs_per_100ft": None,
        "yield_unit": "stems",
        "yield_bunches_per_100ft": 80,
        "wholesale_price_per_lb": None,
        "wholesale_price_per_bunch": 10,
        "organic_premium_pct": 35,
        "jang_seeder": None,
        "feed_class": "flower",
        "rotation_cannot_follow": ["legume"],
        "rotation_prefers_after": ["cover_crop"],
        "interplant_compatible": [],
        "notes": "Highly fragrant spring climbing flower. *NOT edible* (toxic if ingested) — very different from edible peas. Needs trellis support. Must pick continuously to prevent setting seed. Spring-only crop in most climates. Strong florist market for the fragrance alone.",
        "harvest_count": 8,
        "harvest_notes": "Harvest at first open flower on stem. Daily harvesting prolongs production.",
        "csa_lbs_per_share": None,
        "csa_share_unit": "stems",
        "csa_note": "Spring flower CSA staple — fragrance is the selling point.",
        "harvest_frequency": "Every 2-3 days",
        "harvest_method": "Cut with scissors, keep in water immediately",
        "harvest_expectation": "80 stems per 100ft",
        "frost_tolerant": True,
        "hard_frost": False,
        "frost_note": "Plant as soon as soil can be worked. Light frost tolerant. Stops producing in heat.",
        "germination_rate_pct": 0.78,
        "seeds_per_packet": 50,
        "seed_price_usd": 4.49,
        "seed_unit": "seeds",
        "is_special_purchase": False,
        "late_transplant_tolerant": False,
        "planting_method": "Direct Seed",
        "seeds_per_oz": 350,
    },
]


def patch_crops():
    print(f"Loading {CROPS_FILE}...")
    with open(CROPS_FILE, "r") as f:
        data = json.load(f)

    original_count = len(data["crops"])
    crops = copy.deepcopy(data["crops"])

    # ── Step 1: Remove true duplicates ───────────────────────────────────────
    removed = [c for c in crops if c["id"] in REMOVE_IDS]
    crops = [c for c in crops if c["id"] not in REMOVE_IDS]
    print(f"Step 1: Removed {len(removed)} duplicates: {[c['id'] for c in removed]}")

    # ── Step 2: Reclassify misplaced crops ───────────────────────────────────
    reclassified = 0
    for c in crops:
        if c["id"] in RECLASSIFY:
            updates = RECLASSIFY[c["id"]]
            for k, v in updates.items():
                c[k] = v
            reclassified += 1
            print(f"Step 2: Reclassified {c['id']} → {updates}")
    print(f"Step 2: Reclassified {reclassified} crops total")

    # ── Step 3: Fill missing feed_class ──────────────────────────────────────
    filled_fc = 0
    for c in crops:
        if not c.get("feed_class"):
            cat = c.get("category", "")
            fc = CATEGORY_FEED_CLASS.get(cat, "light")
            c["feed_class"] = fc
            filled_fc += 1
    print(f"Step 3: Filled feed_class for {filled_fc} crops")

    # ── Step 4: Add new crops (skip if ID already exists) ────────────────────
    existing_ids = {c["id"] for c in crops}
    added = 0
    for nc in NEW_CROPS:
        if nc["id"] in existing_ids:
            print(f"Step 4: SKIP {nc['id']} — already exists")
            continue
        crops.append(nc)
        added += 1
        print(f"Step 4: Added {nc['id']}")

    # ── Write output ─────────────────────────────────────────────────────────
    data["crops"] = crops
    with open(CROPS_FILE, "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    final_count = len(crops)
    print(f"\n✅ Done!")
    print(f"   Original crop count: {original_count}")
    print(f"   Removed duplicates:  {len(removed)}")
    print(f"   New crops added:     {added}")
    print(f"   Final crop count:    {final_count}")
    print(f"   feed_class filled:   {filled_fc}")
    print(f"   Reclassified:        {reclassified}")


if __name__ == "__main__":
    patch_crops()
